services:
  nginx:
    build: ./requirements/nginx
    image: nginx:42
    container_name: nginx
    ports:
      - 443:443
    depends_on:
     - wordpress
    networks:
    - inception_network
    volumes:
    - wordpress:/var/www/html
    env_file:
     - .env
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:42
    container_name: wordpress
    depends_on:
     - mariadb
    # depend of start DB
    volumes:
      - wordpress:/var/www/html/
    networks:
    - inception_network
    # acces to all $(var)= /.env
    env_file:
      - .env
    secrets:
      - db_password
      - wp_root_password
      - wp_guest_password
    restart: always

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:42
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
    - inception_network
    env_file:
      - .env
    secrets:
     - db_root_password
     - db_password
    restart: always

volumes:
  mariadb:
    # local in (MACHINE)
    driver: local
    # list of param for volume
    driver_opts:
      type: none
      o: bind
        # store volume in target path
      device: /home/thsykas/data/mariadb_volume

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/thsykas/data/wordpress_volume

secrets:
    db_password:
       file: ../secrets/db_password.txt
    db_root_password:
       file: ../secrets/db_root_password.txt
    wp_guest_password:
       file: ../secrets/wp_guest_password.txt
    wp_root_password:
       file: ../secrets/wp_root_password.txt

# network is for make communicate service beetween containeurs
networks:
  inception_network:
    driver: bridge