

events {
	worker_connections 1024;  # connection sim per worker
}

http {
	include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Configuration logs
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

	server {
		listen 443 ssl;
		listen [::]:443 ssl; #ipv6 exec on 443 query
		server_name thsykas.42.fr;

		# ssl_proto find key and certificate
		ssl_certificate /etc/ssl/certs/nginx.crt;
		ssl_certificate_key /etc/ssl/private/nginx.key;

		# crypted protocol (0, 1 security vul) depend of certificate
		ssl_protocols TLSv1.2  TLSv1.3;

		index index.php index.html index.htm; #worpress == .php
		root /var/www/html;

		# uri/ == directory
		# uri == fichier
		
		# e.g if URL = thsykas.42.fr/data.png
			# uri ngnix search /var/www/html/data.png .png ->> png find
			# return png

		location ~* \.(css|js|jpg|jpeg|png|gif|ico|woff2)$ {
			try_files $uri $uri/ =404;
			expires max;
			log_not_found off;
			access_log off;
		}

		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		location ~ \.php$ {
			fastcgi_pass wordpress:9000; # port 9000
			include fastcgi_params;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}
	}
}